export const LOAD_PODCAST_DATA_PENDING  = 'LOAD_PODCAST_DATA_PENDING'
export const LOAD_PODCAST_DATA_SUCCESS  = 'LOAD_PODCAST_DATA_SUCCES'
export const LOAD_PODCAST_DATA_ERROR    = 'LOAD_PODCAST_DATA_ERROR'

